---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# FWSAkRDRtools

<!-- badges: start -->

<!-- badges: end -->

File Management Tools for the Fish & Wildlife Service Alaska Regional Data Repository

## Installation

You can install the development version of FWSAkRDRtools from [GitHub](https://github.com/) with:

``` r
# Install devtools from CRAN
install.packages("devtools")

# Install FWSAkRDRtools from GitHub
devtools::install_github("hdvincelette/FWSAkRDRtools")
```

## USWFS Disclaimer

The United States Fish and Wildlife Service (FWS) GitHub project code is provided on an “as is” basis and the user assumes responsibility for its use. FWS has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality, or availability of the information. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by FWS. The FWS seal and logo shall not be used in any manner to imply endorsement of any commercial product or activity by FWS or the United States Government.

## Getting help

Submit a [GitHub Issue](https://github.com/hdvincelette/FWSAkRDRtools/issues) to report a bug and request a feature or enhancement. Contact the [project maintainer](hannah_vincelette@fws.gov) for information about contributing to this project.
